#97 lap times
Northeastern-Electric-Racing/Nero-2.0 pull request #105
Opened 2024-06-04 22:33 UTC by mattrwang

## Changes

on performance screen, pressing enter starts timer, pressing enter again stops timer and stores info in lap time component

## Notes

currently not working, resetting all to 1

## To Do

_Any remaining things that need to get done_

- [ ] fix resetting to 1 issue

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes #97

2024-06-06 15:34 UTC, Peyton-McKee requested changes

2024-06-06 15:34 UTC, Peyton-McKee commented on NERODevelopment/content/SpeedMode.qml
> +    focus: true
U dont need this. This gets set in the navigation controller

2024-06-06 15:34 UTC, Peyton-McKee commented on NERODesign/content/TimerDisplay.qml
> +            value: "2000"
put this back to 0

2024-06-06 15:34 UTC, Peyton-McKee commented on NERODevelopment/src/controllers/speedcontroller.h
> +  virtual void enterButtonPressed() override;
this is not virtual

2024-06-06 15:45 UTC, Peyton-McKee requested changes
The timer is way way too big, and it is not automatically updating when it should be

2024-06-07 21:08 UTC, jr1221 commented
good to merge?

2024-07-19 01:40 UTC, merged