#45 Off-Screen-Arrange components
Northeastern-Electric-Racing/Nero-2.0 pull request #66
Opened 2024-02-06 02:45 UTC by mliam0608

Created a new screen to represent off screen component.

Added an OffScreen.qml file to the content folder.

![image](https://github.com/Northeastern-Electric-Racing/Nero-2.0/assets/138416854/28bc5c12-d998-427e-9f6a-a88c93caf993)

Closes #45

2024-02-06 04:08 UTC, Peyton-McKee requested changes
all the components within this need to be based on the components height and width, right now everything is fixed which means if we ever want to rearrange things it would be a super pain in the ass

2024-02-06 22:52 UTC, mliam0608 commented
![image](https://github.com/Northeastern-Electric-Racing/Nero-2.0/assets/138416854/2cf6fac0-98de-494f-b576-f952189b912b)

2024-02-08 04:48 UTC, mliam0608 commented
![image](https://github.com/Northeastern-Electric-Racing/Nero-2.0/assets/138416854/4a747490-3d44-40b6-94bb-2becb256562a)

2024-02-08 16:47 UTC, Peyton-McKee requested changes
The design looks good, next step is connecting it to the controller in NERO development

2024-02-08 16:47 UTC, Peyton-McKee commented on NERODesign/content/OffScreen.qml
> +    width: 1024
you should make this 800 by 480 to see what it would actually look like

2024-02-08 16:47 UTC, Peyton-McKee commented on NERODesign/content/OffScreen.qml
> +            shutdownFlowTask: "SIDE BRBs"
the design looks good, you also need to copy this to development and hook up the controller.

2024-02-08 16:47 UTC, Peyton-McKee commented on NERODesign/content/OffScreen.qml
> +            width: parent.width * 0.45
you should make this an actual value because we use it in a whole bunch of places

2024-02-08 16:47 UTC, Peyton-McKee commented on NERODesign/content/OffScreen.qml
> +    visible: true
you also are going to have to link a selectedItem or something so that you can highlight the selected item.

2024-02-22 06:00 UTC, Peyton-McKee commented
https://github.com/Northeastern-Electric-Racing/Nero-2.0/assets/113635669/b9809045-bb56-4a47-93a9-86f0559ad6ee

2024-02-23 22:46 UTC, merged